# Imagen base de Node.js
FROM node:23.11.0-alpine3.21

# Directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia los archivos package.json y package-lock.json
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia todo el código del frontend
COPY . .

# Declara que el contenedor usará el puerto 3000
EXPOSE 3000

# Comando por defecto que se ejecuta cuando el contenedor se inicia
CMD ["npm", "start"]

